### ISSUE TITLE
Не определяет подключение mobile и wifi

### ISSUE THREAD

**Issue by DarkVio** [alexbbb/android-host-monitor#1]
onHostStatusChanged реагирует тока на отсутствие сети... при переключение на wifi или mobile не реагирует.

**Comment by gotev** [comment]
Please write in English here. Translation with google translate:

> responds only to the absence of the network when switching to wifi or mobile does not respond.

In version 1.x the library worked only when your application was in foreground. Now with 2.x it works also when your application is not in foreground and sends correctly events to the registered broadcast receiver. Update your dependencies and check the updated documentation.
