### ISSUE TITLE
Network marked as reachable when it's not

### ISSUE THREAD

**Issue by nicolabeghin** [alexbbb/android-host-monitor#2]
Just to confirm as it should be [standard/unfixed Android behavior](https://code.google.com/p/android/issues/detail?id=40874): if you connect to a host then this becomes unresponsive (es. VPN is interrupted) your library still marks it as "reachable". I just tested it in genymotion by
1. connecting to a host (VPN enabled)
2. disabling VPN
3. accessing the app again and getting

`03-22 12:53:27.489 5612-5612/MyApp I/HostMonitor: {"connectionType":"WIFI","host":"10.10.22.15","port":8021,"previousConnectionType":"NONE","previousReachable":true,"reachable":true}`

It seems like it's not fixable: [ref. issue #82 of ksoap2](https://github.com/simpligility/ksoap2-android/issues/82)

**Comment by gotev** [comment]
Thank you for the detailed issue report. I've seen the links you provided.

By default, android host monitor relies only on the status of the device connectivity and performs checks only when the device connectivity changes (WiFi SSID change, WiFi -> Mobile, Mobile -> WiFi, Mobile -> None, WiFi -> None, ...). 

Android has no way of knowing if you're really connected to the internet or not, unless a "generate 204" request (e.g. `http://clients3.google.com/generate_204`) is performed by the network manager. When it detects no connectivity (the response is different than 204), it will mark the WiFi connection as "without internet" and, starting from Android Lollipop, it will enable mobile data (if you have not explicitly disabled it) to try to provide internet access. In that case, I've noted different behaviours. Sometimes the system launches the CONNECTIVITY_CHANGE event and sometimes not, so you don't have a way of knowing that.

In a scenario like you described, or if you connect to an Access Point, and then you pull the ethernet cable from it, you have no way of being notified of that change, as neither Android OS is aware of that, unless the AP drops the connection or you try a web request.

You can schedule periodic checks in android host monitor, as described in the readme, so if you schedule a check every minute, in the worst case you will be notified that the host went down after a minute, even if your device connectivity has not changed. Unless you have to do active monitoring of a remote system, I discourage doing that, as it's a huge battery drainer, because you're not allowing the radio interface to enter in sleep mode or you are allowing it to enter in that state only for a limited period in time.

In your case I think the best is to make a standalone reachability check to see if the required TCP port on the remote host is still reachable, before performing the other tasks. You can do that with the help of the following class I've written. You can just copy and paste it in your project and it will work.

``` java
import android.content.Context;
import android.os.AsyncTask;

import java.net.InetSocketAddress;
import java.net.Socket;

/**
 * Utility async task to check port reachability.
 *
 * @author Alex Gotev
 */
public class TcpPortReachabilityCheck extends AsyncTask<Void, Void, Boolean> {

    public interface Delegate {
        void beforeCheck();
        void afterCheck(boolean reachable);
    }

    private final Context mContext;
    private final String mHost;
    private int mPort;
    private int mMaxAttempts;
    private Delegate mDelegate;

    public TcpPortReachabilityCheck(Context context, String host, int port, int maxAttempts) {
        mContext = context;
        mHost = host;
        mPort = port;
        mMaxAttempts = maxAttempts > 1 ? maxAttempts : 1;
    }

    public TcpPortReachabilityCheck setDelegate(Delegate delegate) {
        if (delegate != null)
            mDelegate = delegate;

        return this;
    }

    public TcpPortReachabilityCheck(Context context, String host, int port) {
        this(context, host, port, 2);
    }

    @Override
    protected void onPreExecute() {
        super.onPreExecute();
        if (mDelegate != null)
            mDelegate.beforeCheck();
    }

    @Override
    protected Boolean doInBackground(Void... params) {

        boolean reachable = false;
        int attempts = 1;

        while (attempts < mMaxAttempts) {
            reachable = isReachable();
            if (reachable) break;
            attempts++;
        }

        return reachable;
    }

    @Override
    protected void onPostExecute(Boolean aBoolean) {
        super.onPostExecute(aBoolean);
        if (mDelegate != null)
            mDelegate.afterCheck(aBoolean);
    }

    private boolean isReachable() {
        boolean currentReachable;
        Socket socket = null;

        try {
            socket = new Socket();
            socket.connect(new InetSocketAddress(mHost, mPort), 3000);
            currentReachable = true;

        } catch (Exception exc) {
            currentReachable = false;

        } finally {
            if (socket != null) {
                try {
                    socket.close();
                } catch (Exception ignored) { }
            }
        }

        return currentReachable;
    }
}
```

You can use it in an Activity in this way:

``` java
// Check if TCP port 3000 is reachable on 192.168.1.7. 
// If it's not reachable for 3 times in a row, then notify unreachability
new TcpPortReachabilityCheck(Activity.this, "192.168.1.7", 3000, 3)
                        .setDelegate(Activity.this).execute();
```

by replacing `Activity.this` with your activity context and implementing `TcpPortReachabilityCheck.Delegate` like this:

``` java
@Override
public void beforeCheck() {
    Toast.makeText(this, "Performing check", Toast.LENGTH_SHORT).show();
}

@Override
public void afterCheck(boolean reachable) {
    Toast.makeText(this, "Host is " + (reachable ? "reachable" : "unreachable"), 
                         Toast.LENGTH_SHORT).show();
}
```

I've tested this on my home network with a process listening on the port 3000 of my computer. When the process is up and I perform the reachability check, it's successful. When I kill the process or disable my computer's WiFi interface and retry the test, the check correctly notifies that the TCP port is unreachable. Try that and let me know, so if it's useful I will add the class into the library for cases like this when standalone checks are needed.

**Comment by nicolabeghin** [comment]
Hi @gotev thanks so much for your detailed reply! 
Below my points:

> In a scenario like you described, or if you connect to an Access Point, and then you pull the ethernet cable from it, you have no way of being notified of that change, as neither Android OS is aware of that, unless the AP drops the connection or you try a web request.

that's exactly how I used your library
`new HostMonitorConfig(context).setCheckIntervalInMinutes(15).save();`

About the suggested way to check host reachability with
`socket.connect(new InetSocketAddress(mHost, mPort), 3000);`

That's one of the things I tried before opening the ticket, like

```
SocketAddress.connect(host,timeout)
InetAddress.getByName().isReachable 
AsyncTask + AsyncTask with CountDownTime
FutureTask
postDelay + task cancellation
```

In particular `SocketAddress.connect(host,timeout)` gave me false results (reached the timeout giving a successful connection, even if the host wasn't really reachable).

This [SO thread](http://stackoverflow.com/questions/12383854/how-to-stop-httpurlconnection-connect-on-android/26489077#26489077) was particularly helpful, as it helped me understand the underlying issue: if `HttpUrlConnection.setTimeout(int)` [is bugged (from years)](https://code.google.com/p/android/issues/detail?id=40874) you can't do anything to stop the connection even if you want it. A connection request is gonna stay alive until the timeout is reached, and this causes all sorts of problems with your activity lifecycle (in my case it causes the `Activity` to hangs until the connection times out). Please note, this happens _with non-existent hosts only or recently unreachable hosts_ (like when you unplug the ethernet cable or the wifi networks is suddenly not responding anymore). 

You can test it yourself with the snipped I posted in [https://github.com/simpligility/ksoap2-android/issues/82#issuecomment-199736505](https://github.com/simpligility/ksoap2-android/issues/82#issuecomment-199736505)

The only workaround (I still have to test) is to switch the network library to the (recently deprecated) Apache `DefaultHttpClient`, which should have a thread-safe `abort()` method.

Looking forward to hear back from you about this (surprisingly) old issue.

**Comment by gotev** [comment]
The issue is clearer now, thanks for the explanation :+1: 
Apache Http Client is the past. You can try with [OkHttp](https://github.com/square/okhttp), which is an excellent networking library that has been written from scratch and does not rely on existing system (bugged) libraries. I use it in many projects and it's a very well written library. I know for sure that requests made with OkHttp can be interrupted, but some tests have to be made in the described scenario to see how it behaves. Looking forward to hear from you!

**Comment by nicolabeghin** [comment]
being `HttpUrlConnection` suggested Android's network API, `OkHttp` uses it too so we're back to square one. Interrupt requests are ok but only when the connection to host is already established/the host has been resolved/has replied, not when the connection is in the process of being established (CONNECTING or similar). Maybe older is better in this case :-)

```
03-22 11:20:58.401 7042-7309/MyApp E/MyAppDeskApp: Error: sendto failed: ETIMEDOUT (Connection timed out)
03-22 11:20:58.401 7042-7309/MyApp W/System.err: java.net.SocketException: sendto failed: ETIMEDOUT (Connection timed out)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:499)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:468)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.net.PlainSocketImpl.write(PlainSocketImpl.java:507)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:269)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.splunk.mint.network.io.OutputStreamMonitor.write(OutputStreamMonitor.java:54)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:85)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.android.okhttp.internal.http.HttpTransport.flushRequest(HttpTransport.java:107)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:642)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:179)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.altevie.MyApp.deskapp.UsersActivity$TestTask.doInBackground(UsersActivity.java:229)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.altevie.MyApp.deskapp.UsersActivity$TestTask.doInBackground(UsersActivity.java:214)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.lang.Thread.run(Thread.java:841)
03-22 11:20:58.401 7042-7309/MyApp W/System.err: Caused by: libcore.io.ErrnoException: sendto failed: ETIMEDOUT (Connection timed out)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at libcore.io.Posix.sendtoBytes(Native Method)
03-22 11:20:58.405 7042-7309/MyApp W/System.err:     at libcore.io.Posix.sendto(Posix.java:156)
03-22 11:20:58.405 7042-7309/MyApp W/System.err:     at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
03-22 11:20:58.405 7042-7309/MyApp W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:466)
03-22 11:20:58.405 7042-7309/MyApp W/System.err:    ... 19 more
```

**Comment by gotev** [comment]
> being HttpUrlConnection suggested Android's network API, OkHttp uses it too so we're back to square one. 

No, that's not true. OkHttp, as I told you in my previous post, implements everything from scratch and does not rely on the existing `HttpUrlConnection` implementation. In fact, it's so good, that as of [Android 4.4](https://twitter.com/JakeWharton/status/482563299511250944), OkHttp implementation has been used to provide the `HttpUrlConnection` class. However, the version included in 4.4 is very old, so the best you can do is to add the latest OkHttp in your dependencies, use it and forget about `HttpUrlConnection` and Apache Clients. This way you will have a consistent behaviour, no matter on which Android version your app is running. Another point in favor of OkHttp is that you will write less and more readable code to do the same things :grin:

I've used your snippet from simpligility/ksoap2-android#82 to make a test on Android 6.0.1. These are the results:

```
I/TestTask: starting connection to http://217.19.150.253:80
E/TestTask: Error: failed to connect to /217.19.150.253 (port 80) after 4000ms
W/System.err: java.net.SocketTimeoutException: failed to connect to /217.19.150.253 (port 80) after 4000ms
W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
W/System.err:     at java.net.Socket.connect(Socket.java:884)
W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
W/System.err:     at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
W/System.err:     at com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:152)
W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
W/System.err:     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
W/System.err:     at net.gotev.tester.TestTask.doInBackground(TestTask.java:27)
W/System.err:     at net.gotev.tester.TestTask.doInBackground(TestTask.java:11)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

and

```
E/TestTask: Error: Unable to resolve host "wwww.goooooooooooeoeoeoeoel.com": No address associated with hostname
W/System.err: java.net.UnknownHostException: Unable to resolve host "wwww.goooooooooooeoeoeoeoel.com": No address associated with hostname
W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:215)
W/System.err:     at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
W/System.err:     at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:188)
W/System.err:     at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:157)
W/System.err:     at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:100)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:357)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:340)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
W/System.err:     at net.gotev.tester.TestTask.doInBackground(TestTask.java:27)
W/System.err:     at net.gotev.tester.TestTask.doInBackground(TestTask.java:11)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/System.err:     at libcore.io.Posix.android_getaddrinfo(Native Method)
W/System.err:     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
W/System.err:   ... 21 more
```

Then, I've implemented an async task which does the same, but with the latest OkHttp.
Just add `compile 'com.squareup.okhttp3:okhttp:3.2.0'` in your gradle dependencies

``` java
import android.os.AsyncTask;
import android.util.Log;

import java.net.URL;
import java.util.concurrent.TimeUnit;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

/**
 * @author Aleksandar Gotev
 */
public class TestTaskOkHttp extends AsyncTask<String, Void, String> {
    @Override
    protected void onPreExecute() {
        super.onPreExecute();
    }

    @Override
    protected String doInBackground(String... qrcodes) {
        try {
            OkHttpClient client = new OkHttpClient.Builder()
                    .connectTimeout(4, TimeUnit.SECONDS)
                    .readTimeout(4, TimeUnit.SECONDS)
                    .build();

            // "http://wwww.goooooooooooeoeoeoeoel.com"
            Request request = new Request.Builder()
                    .url(new URL("http://217.19.150.253:80"))
                    .build();

            Response response = client.newCall(request).execute();
            return response.body().string();

        } catch (Exception e) {
            Log.e(getClass().getSimpleName(), "Exception in Task: " + e.getMessage());
            return null;
        }
    }
}
```

and the results are:

```
E/TestTaskOkHttp: Exception in Task: failed to connect to /217.19.150.253 (port 80) after 4000ms
```

```
E/TestTaskOkHttp: Exception in Task: Unable to resolve host "wwww.goooooooooooeoeoeoeoel.com": No address associated with hostname
```

Try that and let me know. I'm pretty confident that it will work.

**Comment by nicolabeghin** [comment]
That's awesome news! I'll get down to it and let you know. Best thing (as pointed out in the ksoap2 thread) would be to use OkHttp's UrlConnection implementation, and I'll see if that's feasible, in order to avoid having to pre-check host reachability.

Thanks a lot.

**Comment by nicolabeghin** [comment]
Hi @gotev I confirm your suggestion [works absolutely ok](https://github.com/simpligility/ksoap2-android/issues/82#issuecomment-202854933), `OkHttp3` does the work! Do you plan on reworking the active network monitor with `OkHttp3` in 
[HostMonitor.java#L187](https://github.com/gotev/android-host-monitor/blob/master/hostmonitor/src/main/java/net/gotev/hostmonitor/HostMonitor.java#L187)? I was trying to do it myself but can't import the library on Android Studio.

**Comment by gotev** [comment]
@nicolabeghin Surely it's a good improvement. I'm very busy in this period and I don't have time to spend on this modification. If you have it, I'll be glad to accept your pull request.

Regarding Android Studio, it's really strange. Try the following. Open a terminal and clone the repository

```
git clone https://github.com/gotev/android-host-monitor.git
```

From Android Studio (I use 1.5.1 on OS X) `File > Open...`, then select the directory in which you have done the checkout. After some loading, just click on `Project` and you should see the classes and be able to compile. If it works, just fork the project, create a new branch, check it out and do the required modifications.

**Comment by nicolabeghin** [comment]
I was able to import the library. Pull request #4  sent, hope it can help your library spread!
