### ISSUE TITLE
Periodic reachability check not working

### ISSUE THREAD

**Issue by nicolabeghin** [alexbbb/android-host-monitor#5]
Hi @gotev 
I would like to  know if there is something wrong with this configuration. I don't get periodic reachability checks, reachability is checked only the first time `Activity` is shown.

I'm using the extended okhttp3 reachability at [https://github.com/nicolabeghin/android-host-monitor](https://github.com/nicolabeghin/android-host-monitor) but this happened using the "stock" version of the library too. 

Maybe your library checks for reachability only when Android notifies/broadcast some kind of network change? 

``` java
import net.gotev.hostmonitor.HostMonitorBroadcastReceiver;
import net.gotev.hostmonitor.HostMonitorConfig;
import net.gotev.hostmonitor.HostStatus;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

/**
 * Created by nbeghin on 03/06/2015.
 */
public abstract class AbstractBaseActivity extends AppCompatActivity {
    public HostMonitorBroadcastReceiver receiver;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        receiver = new HostMonitorBroadcastReceiver() {
            @Override
            public void onHostStatusChanged(HostStatus status) {
                Log.i("INTERNAL HostMonitor", status.toString());
                Toast.makeText(AbstractBaseActivity.this, "CRM "+(status.isReachable()==false?"non":"")+" raggiungibile", Toast.LENGTH_SHORT).show();
                if (status.isReachable()!=status.isPreviousReachable()) {
                    Toast.makeText(AbstractBaseActivity.this, "CRM "+(status.isReachable()==false?"non":"")+" raggiungibile", Toast.LENGTH_SHORT).show();
                } else {

                }
            }

            @Override
            public void onReceive(Context context, Intent intent) {
                super.onReceive(context, intent);
                Log.i("INTERNAL HostMonitor", "onReceive");
            }
        };
        HostMonitorConfig.reset(this);
        new HostMonitorConfig(this)
                .setBroadcastAction(getString(R.string.broadcast_action_network_host_monitor))
                .setCheckIntervalInSeconds(10)
                .add(Constants.HOST, Integer.parseInt(Constants.PORT))
                .setSocketTimeoutInMilliseconds(1000)
                .save();
        Log.w(MainActivity.AppName, getClass().getName() + " onCreate");
    }

    @Override
    protected void onResume() {
        super.onResume();
        receiver.register(this);
        Log.w(MainActivity.AppName, getClass().getName() + " onResume");
    }

    @Override
    protected void onStart() {
        super.onStart();
        Log.w(MainActivity.AppName, getClass().getName() + " onStart");
    }

    @Override
    protected void onStop() {
        super.onStop();
        Log.w(MainActivity.AppName, getClass().getName() + " onStop");
    }

    @Override
    protected void onPause() {
        super.onPause();
        receiver.unregister(this);
        Log.w(MainActivity.AppName, getClass().getName() + " onPause");
    }

}

```

```
03-29 18:53:24.058 23055-23055/testapp D/HostMonitor: reset configuration
03-29 18:53:24.086 23055-23055/testapp D/HostMonitor: cancelling scheduled checks
03-29 18:53:24.086 23055-23055/testapp D/HostMonitorConfig: saving configuration
03-29 18:53:24.130 23055-23055/testapp D/HostMonitor: cancelling scheduled checks
03-29 18:53:24.130 23055-23055/testapp D/HostMonitorConfig: scheduling periodic checks every 10 seconds
03-29 18:53:24.130 23055-23055/testapp D/HostMonitorConfig: triggering reachability check
03-29 18:53:24.658 23055-23100/testapp D/HostMonitor: Starting reachability check
03-29 18:53:24.862 23055-23100/testapp D/HostMonitor: Host 10.10.22.15 is currently reachable on port 8021 via WIFI
03-29 18:53:24.866 23055-23100/testapp D/HostMonitor: Broadcast with action: com.altevie.bocconi.deskapp.prd and status: {"connectionType":"WIFI","host":"10.10.22.15","previousConnectionType":"NONE","port":8021,"previousReachable":true,"reachable":true}
03-29 18:53:24.866 23055-23100/testapp D/HostMonitorConfig: saving hosts status map
03-29 18:53:24.870 23055-23100/testapp D/HostMonitor: Reachability check finished!
03-29 18:53:25.694 23055-23055/testapp I/INTERNAL HostMonitor: {"connectionType":"WIFI","host":"10.10.22.15","previousConnectionType":"NONE","port":8021,"previousReachable":true,"reachable":true}
03-29 18:53:25.706 23055-23055/testapp I/INTERNAL HostMonitor: onReceive
```

**Comment by gotev** [comment]
This behaviour is due to how you have used the library. With the code you posted, the library depends on your Activity's lifecycle. When the activity gets destroyed, its context gets destroyed, too. Maybe you want the library to depend on your Application lifecycle instead, in which case you have to perform the initialization in the Application subclass (example from my other library: https://github.com/gotev/android-upload-service/wiki/Setup), and then you have to implement a global broadcast receiver, like explained here: https://github.com/gotev/android-host-monitor#receive-reachability-status-changes-

**Comment by nicolabeghin** [comment]
I don't know if I understood correctly but since the activity is running the periodic check should be running, isn't that true? I don't need checks to be application-wise, I just want them to be running while the activity is live.

I even tried with the receiver registered in the `AndroidManifest.xml` but I wasn't able to get it working neither. The action intent is surely ok as I used a resource string value.

**Comment by gotev** [comment]
The periodic checks should run when your activity is running. Underneath, the library uses the AlarmManager's [setRepeating](http://developer.android.com/reference/android/app/AlarmManager.html#setRepeating%28int,%20long,%20long,%20android.app.PendingIntent%29) method to perform the check. I think that it doesn't like intervals lower than 60 seconds from tests I've made when developing the library.

Regarding the BroadcastReceiver, check what you have implemented, because I'm sure it works when you create a new class which extends the base class provided in the library, and then you register it in your manifest.

**Comment by nicolabeghin** [comment]
I'll try with an higher time interval (I'm using 10 seconds), but I need such a little interval so maybe I'll need to revert to something else if this is an Android-related constraint.

About the BroadcastReceiver: I prefer the in-activity receiver. thanks for your support anyway.

**Comment by gotev** [comment]
Not to enter in a software design discussion, as I don't even know what you are trying to achieve, but instead of performing checks so frequently, maybe you should simply manage http requests failure. It will drain you battery a lot less. If you need this to poll a server (for a social app for example), consider moving on something newer and cooler like web sockets.

**Comment by nicolabeghin** [comment]
@gotev I perfectly understand and I would never use such an extreme measure but my client is an enterprise running time-restrained events during which server availability needs to be checked as soon as possible. websocket is cool but not widespread in those legacy environments (we're talking SAP), plus battery is not an issue. Thanks for your interest anyway!

**Comment by nicolabeghin** [comment]
@gotev, just to understand your architecture: is there any reason why you used the [AlarmManager](http://developer.android.com/reference/android/app/AlarmManager.html) in place of [Handler](http://developer.android.com/reference/android/os/Handler.html) as suggested in official Android docs? 

`
Note: The Alarm Manager is intended for cases where you want to have your application code run at a specific time, even if your application is not currently running. For normal timing operations (ticks, timeouts, etc) it is easier and much more efficient to use Handler.`

Please don't take it as a criticism, I just want to understand what's the best approach for periodic background checks!

**Comment by gotev** [comment]
The library has been designed to work in background to keep alive some background services even when the main app is not running, so AlarmManager is needed to be able to perfom the checks. If you need to perform frequent checks inside an activity, it's not the best option, as suggested by the Android docs.

**Comment by nicolabeghin** [comment]
Thanks for the clarification, it seems reasonable.

**Comment by gotev** [comment]
@nicolabeghin your use case made me think about an extension to the library. What I thought of is to implement a new class which performs the checks using the same logic, but with the difference that it doesn't use AlarmManager, in favor of an ExecutorService or Handler. In this way when you instantiate and run this class inside an activity or service, you can have much more frequent checks, and you can leave the Broadcast listener implementation unchanged, as it will receive the same events. What do you think about this idea?

**Comment by nicolabeghin** [comment]
Excellent idea. I switched to services for network layer in all my projects (Robospice) and they're excellent for background/long running tasks.
