### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by garudaonekh** [alexbbb/android-host-monitor#7]
Hi,
If I I use initialize the monitor in an activity using broadcastreceiver( init in manifest), will the broadcast be still fired when the activity is destroyed?

And what if I use Application as context?

Thanks;

**Comment by gotev** [comment]
> will the broadcast be still fired when the activity is destroyed?

no, as per Android activity lifecycle

> And what if I use Application as context?

In that case you should not do that and implement it as a global broadcast receiver and register it in your manifest

**Comment by garudaonekh** [comment]
Why I should not use Application as context?

**Comment by gotev** [comment]
Because if you need the application context it means you need a global broadcast receiver
